f=open('d:\\App\\AgentProjects\\likecodex\\likecodex\\packages\\likecodex-engine\\likecodex_engine\\agent\\loop.py','rb')
r=f.read()
f.close()
old=b'            # Watchdog: check if stuck (no tool calls for 5 minutes)\n            now = time.time()\n            if self._used_any_tool and (now - self._last_activity_time) > 300:\n                yield self._emit(\n                    LLMResponse(\n                        content="[watchdog] No tool calls for 5 minutes. Injecting prompt to check if stuck.",\n                        model="system",\n                        event_type="notice",\n                    )\n                )\n                self._last_activity_time = now\n            self._last_activity_time = now\n            \n            # Prefetch'
new=b'            # Watchdog: periodic check (15s interval) with 5min timeout\n            now = time.time()\n            elapsed = now - self._start_time\n            idle_time = now - self._last_activity_time\n\n            # 5-minute absolute timeout\n            if elapsed > 300 and self._used_any_tool:\n                yield self._emit(\n                    LLMResponse(\n                        content="[watchdog] Total execution time exceeded 5 minute timeout. Forcing termination.",\n                        model="system",\n                        event_type="watchdog_timeout",\n                        metadata={\n                            "elapsed_s": round(elapsed, 1),\n                            "idle_s": round(idle_time, 1),\n                            "action": "timeout_termination",\n                        },\n                    )\n                )\n                hit_max_iterations = True\n                break\n\n            # Idle detection\n            if idle_time > 15 and self._used_any_tool:\n                if not self._watchdog_fired:\n                    self._watchdog_fired = True\n                    yield self._emit(\n                        LLMResponse(\n                            content=f"[watchdog] Idle for {idle_time:.0f}s. Checking if stuck.",\n                            model="system",\n                            event_type="watchdog_check",\n                            metadata={\n                                "elapsed_s": round(elapsed, 1),\n                                "idle_s": round(idle_time, 1),\n                                "action": "idle_check",\n                            },\n                        )\n                    )\n                if idle_time > 60:\n                    yield self._emit(\n                        LLMResponse(\n                            content="[watchdog] Extended idle detected. Attempting to re-engage the model.",\n                            model="system",\n                            event_type="watchdog_idle",\n                            metadata={\n                                "elapsed_s": round(elapsed, 1),\n                                "idle_s": round(idle_time, 1),\n                                "action": "idle_nudge",\n                            },\n                        )\n                    )\n                    self._last_activity_time = now\n                    self._watchdog_fired = False\n            else:\n                self._watchdog_fired = False\n            self._last_activity_time = now\n\n            # Prefetch'
if old in r:
    r=r.replace(old,new,1)
    f=open('d:\\App\\AgentProjects\\likecodex\\likecodex\\packages\\likecodex-engine\\likecodex_engine\\agent\\loop.py','wb')
    f.write(r)
    f.close()
    print('OK')
else:
    print('NOT FOUND')
