with open('d:\\App\\AgentProjects\\likecodex\\likecodex\\packages\\likecodex-engine\\likecodex_engine\\agent\\loop.py', 'rb') as f:
    raw = f.read()

old = b'            # Watchdog: check if stuck (no tool calls for 5 minutes)\r\n            now = time.time()\r\n            if self._used_any_tool and (now - self._last_activity_time) > 300:\r\n                yield self._emit(\r\n                    LLMResponse(\r\n                        content="[watchdog] No tool calls for 5 minutes. Injecting prompt to check if stuck.",\r\n                        model="system",\r\n                        event_type="notice",\r\n                    )\r\n                )\r\n                self._last_activity_time = now\r\n            self._last_activity_time = now\r\n            \r\n            # Prefetch'

new = b'            # Watchdog: periodic check (15s interval) with 5min timeout\r\n            now = time.time()\r\n            elapsed = now - self._start_time\r\n            idle_time = now - self._last_activity_time\r\n\r\n            # 5-minute absolute timeout\r\n            if elapsed > self._watchdog_timeout and self._used_any_tool:\r\n                yield self._emit(\r\n                    LLMResponse(\r\n                        content="[watchdog] Total execution time exceeded 5 minute timeout. Forcing termination.",\r\n                        model="system",\r\n                        event_type="watchdog_timeout",\r\n                        metadata={\r\n                            "elapsed_s": round(elapsed, 1),\r\n                            "idle_s": round(idle_time, 1),\r\n                            "action": "timeout_termination",\r\n                        },\r\n                    )\r\n                )\r\n                hit_max_iterations = True\r\n                break\r\n\r\n            # Idle detection\r\n            if idle_time > self._watchdog_check_interval and self._used_any_tool:\r\n                if not self._watchdog_fired:\r\n                    self._watchdog_fired = True\r\n                    yield self._emit(\r\n                        LLMResponse(\r\n                            content=f"[watchdog] Idle for {idle_time:.0f}s. Checking if stuck.",\r\n                            model="system",\r\n                            event_type="watchdog_check",\r\n                            metadata={\r\n                                "elapsed_s": round(elapsed, 1),\r\n                                "idle_s": round(idle_time, 1),\r\n                                "action": "idle_check",\r\n                            },\r\n                        )\r\n                    )\r\n                if idle_time > 60:\r\n                    yield self._emit(\r\n                        LLMResponse(\r\n                            content="[watchdog] Extended idle detected. Attempting to re-engage the model.",\r\n                            model="system",\r\n                            event_type="watchdog_idle",\r\n                            metadata={\r\n                                "elapsed_s": round(elapsed, 1),\r\n                                "idle_s": round(idle_time, 1),\r\n                                "action": "idle_nudge",\r\n                            },\r\n                        )\r\n                    )\r\n                    self._last_activity_time = now\r\n                    self._watchdog_fired = False\r\n            else:\r\n                self._watchdog_fired = False\r\n            self._last_activity_time = now\r\n\r\n            # Prefetch'

if old in raw:
    raw = raw.replace(old, new, 1)
    with open('d:\\App\\AgentProjects\\likecodex\\likecodex\\packages\\likecodex-engine\\likecodex_engine\\agent\\loop.py', 'wb') as f:
        f.write(raw)
    print('Replaced successfully')
else:
    print('Old watchdog pattern not found in binary')
    idx = raw.find(b'Watchdog: check')
    if idx >= 0:
        print('Found at', idx)
        print(raw[idx:idx+200])
